contact/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index")
]

mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^contact/', include('contact.urls', namespace="contact")),
    url(r'^admin/', admin.site.urls),
]

contact/models.py
from django.db import models

# Create your models here.


class PostModel(models.Model):
    nama = models.CharField(max_length=20)
    gender = models.CharField(max_length=20)
    email = models.EmailField()
    alamat = models.CharField(max_length=200)
    #agree = models.BooleanField()
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}. {}".format(self.id, self.nama)

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    nama = forms.CharField(
        max_length=20,
        label="Nama",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Masukkan nama anda',
            }
        )
    )

    JENIS_KELAMIN = (
        ('P', 'Pria'),
        ('W', 'Wanita')
    )
    gender = forms.ChoiceField(
        widget=forms.RadioSelect(
            attrs={
                'class': 'form-check-input',
            }
        ),
        choices=JENIS_KELAMIN
    )

    email = forms.EmailField(
        label="Alamat Email",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Masukkan email anda'
            }
        )
    )

    alamat = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        )
    )

    # agree = forms.BooleanField(
    #    required=False,
    #    widget=forms.CheckboxInput(
    #        attrs={
    #            'class': 'form-check-input',
    #        }
    #    )
    # )

    #TAHUN = range(1945, 2021, 1)
    # tanggal_lahir = forms.DateField(
    #    widget=forms.SelectDateWidget(
    #        attrs={
    #            'class': 'form-control col-sm-2'
    #        },
    #        years=TAHUN,
    #    )
    # )

    def clean_nama(self):
        nama_input = self.cleaned_data.get('nama')

        if nama_input == "memek":
            raise forms.ValidationError("nama tidak boleh memek")

        return nama_input

contact/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.

from .forms import ContactForm
from .models import PostModel


def index(request):
    contact_form = ContactForm(request.POST or None)
    error = None

    if request.method == 'POST':

        if contact_form.is_valid():
            PostModel.objects.create(
                nama=contact_form.cleaned_data.get('nama'),
                gender=contact_form.cleaned_data.get('gender'),
                email=contact_form.cleaned_data.get('email'),
                alamat=contact_form.cleaned_data.get('alamat'),
                # agree=request.POST['agree'],
                # tanggal_lahir=request.POST['tanggal_lahir'],
            )
            return HttpResponseRedirect("/")
        else:
            error = contact_form.errors

    context = {
        'Heading': 'Contact Form',
        'contact_form': contact_form,
        'error': error,
    }
    return render(request, 'contact/index.html', context)

mywebsite/views.py
from django.shortcuts import render

from contact.models import PostModel


def index(request):
    contact_data = PostModel.objects.all()
    context = {
        'Heading': 'Home Form',
        'Contact': contact_data,
    }
    if request.method == 'POST':
        context['nama'] = request.POST['nama']
        context['alamat'] = request.POST['alamat']

    return render(request, 'index.html', context)

contact/templates/contact/index.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1>{{Heading}}</h1>

    <div class="container">

        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
        <form method="post">
            {% csrf_token %}
            <h1>HAHA</h1>
            <div class="form-group">
                {{ contact_form.nama.label_tag}}
                {{ contact_form.nama}}
            </div>

            <div class="form-group">
                {{ contact_form.gender.label_tag}}
                {% for component in contact_form.gender %}
                <div class="form-check">
                    {{component.tag}}
                    <label for="{{component.id_for_label}}" class="form-check-label">
                        {{component.choice_label}}
                    </label>
                </div>
                {% endfor %}
            </div>

            <div class="form-group">
                {{contact_form.tanggal_lahir.label_tag}}
                <div class="form-row">
                    {{contact_form.tanggal_lahir}}
                </div>
            </div>

            <div class="form-group">
                {{ contact_form.email.label_tag}}
                {{ contact_form.email}}
            </div>

            <div class="form-group">
                {{ contact_form.alamat.label_tag}}
                {{ contact_form.alamat}}
            </div>

            <div class="form-group">
                <div class="form-check">
                    {{ contact_form.agree}}
                    <label for="{{contact_form.agree.id_for_label}}">{{ contact_form.agree.label}}</label>
                </div>
            </div>
            <!-- <table>
                {{contact_form.as_table}}
            </table> -->
            <br>
            <button type=" submit">Submit</button>
        </form>
    </div>

</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{Heading}}</title>
    {% include "snippets/styles.html" %}
</head>

<body>
    {% include "snippets/navbar.html" %}

    {% block content %}

    {% endblock content %}

    {% include "snippets/scripts.html" %}
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1>{{Heading}}</h1>
    <hr>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Gender</th>
                <th scope="col">Email</th>
                <th scope="col">Address</th>
            </tr>
        </thead>

        {% for contact in Contact %}
        <tbody>
            <tr>
                <th scope="row">{{contact.nama}}</th>
                <td>{{contact.gender}}</td>
                <td>{{contact.email}}</td>
                <td>{{contact.alamat}}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>

</div>
{% endblock content %}

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Uber</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url "index" %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "contact:index" %}">Add Data</a>
            </li>
        </ul>
    </div>
</nav>

templates/snippets/scripts.html
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>

templates/snippets/styles.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">